version: "3"
services:
  mongo:
    image: mongo
    container_name: my-mongodb
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: app
    volumes:
      - mongodb:/data/db
      - mongodb-config:/data/configdb
volumes:
  mongodb:
  mongodb-config:
